# Dockerfile (Flask AppBuilder)
FROM python:3.9-slim

WORKDIR /app

# Copiar o arquivo de dependências
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o código do app.py
COPY app.py /app/

# Aguardar 1 segundo antes de iniciar o Flask
CMD ["sh", "-c", "sleep 1 && flask run --host=0.0.0.0"]
